---
- name: Create file references
  set_fact:
    script_file_path: "{{ role_path }}/files/add-{{ repo_type | lower }}-{{ resource_type | lower }}-repository.groovy"

- name: Process groovy script with Jinja and replace newlines
  set_fact:
    groovy_script: "{{ lookup('file', script_file_path) }}"
    member_string: "{{ members | default('') }}"

- name: Group facts
  set_fact:
    json_data:
      name: "{{ resource_name }}"
      type: 'groovy'
      content: "{{ groovy_script }}"
    postParams:
      proxyUrl: "{{ proxy_url | default('') }}"
      members: "{{ member_string.split(',') }}"
      name: "{{ resource_name }}"
      strictContentTypeValidation: "{{ strict_content | default('false') }}"
      writePolicy: "{{ write_policy | default('allow') }}"
      v1Enabled: "{{ v1_enabled | default('false') }}"
      httpPort: "{{ docker_http_port | default('') }}"
      httpsPort: "{{ docker_https_port | default('') }}"
      versionPolicy: "{{ version_policy | default('release') }}"
      layoutPolicy: "{{ layout_policy | default('strict') }}"

- name: Wrap groovy script in JSON body
  set_fact:
    json_body: "{{ json_data | to_json }}"

- name: Add script if needed
  block:
  - name: "Check For Existing Script: {{ resource_name }}"
    uri:
      url: "{{ nexus_protocol }}://{{ nexus_url }}{{ nexus_api_base_path }}/script/{{ resource_name }}"
      method: GET
      user: "{{ nexus_user }}"
      password: "{{ nexus_password }}"
      force_basic_auth: yes
      status_code: 200,404
      validate_certs: false
    register: get_script_result
  rescue:
  - name: "Create New Script: {{ resource_name }}"
    uri:
      url: "{{ nexus_protocol }}://{{ nexus_url }}{{ nexus_api_base_path }}/script/"
      method: POST
      user: "{{ nexus_user }}"
      password: "{{ nexus_password }}"
      body_format: json
      body: "{{ json_body }}"
      force_basic_auth: yes
      validate_certs: false
      status_code: '204'

- name: "Execute New Script: {{ resource_name }}"
  uri:
    url: "{{ nexus_protocol }}://{{ nexus_url }}{{ nexus_api_base_path }}/script/{{ resource_name }}/run"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    headers:
      Content-Type: "text/plain"
    body: "{{ postParams | to_json }}"
    force_basic_auth: yes
    validate_certs: false
    status_code: 200
