---
nexus_protocol: https
nexus_user: admin
nexus_default_password: admin123
nexus_password: admin123
nexus_server_poll_retries: 100
nexus_server_poll_delay_in_seconds: 5
nexus_api_base_path: /service/siesta/rest/v1
nexus_validate_certs: true
nexus_repos:
- script_name: redhat-repos
  script_file: redhat-repos-script.groovy
- script_name: custom-repos
  script_file: custom-repos-script.groovy
- script_name: nist-proxy-repos
  script_file: nist-proxy-repos.groovy
